import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import ClientOnly from '@/components/ClientOnly';
import './globals.css';

const poppins = Poppins({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata: Metadata = {
    title: 'Shopping Store',
    description: 'Generated by create store application'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <ClientOnly>{children}</ClientOnly>
            </body>
        </html>
    );
}
